services:
  jupyterlab:
    build: .
    ports:
      - "127.0.0.1:8888:8888"
    working_dir: "/project"
    environment:
      IPYTHONDIR: "/.ipython"
    volumes:
      - "./:/project"
      - "jupyterlab-local:/.local"
      - "jupyterlab-data:/.jupyter"
      - "jupyterlab-config:/.config"
      - "jupyterlab-cache:/.cache"
      - "jupyterlab-ipython:/.ipython"

volumes:
  jupyterlab-local: {}
  jupyterlab-data: {}
  jupyterlab-config: {}
  jupyterlab-cache: {}
  jupyterlab-ipython: {}
